version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: e-commerse
      MONGO_INITDB_ROOT_PASSWORD: e-commerse
      MONGO_INITDB_DATABASE: chat_app
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: