spring.application.name=e-commerse-be
server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d74kp56uk2gs73a75s1g-a.singapore-postgres.render.com/e_commerse_db_yq4z
spring.datasource.username=e_commerse_db_yq4z_user
spring.datasource.password=kkblubFN4ndMsnTmDBMWfGzeTlI5bpof
#spring.datasource.url=jdbc:postgresql://localhost:5432/e_commerse
#spring.datasource.username=postgres
#spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# jwt configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.access-token-expiration=86400000
application.security.jwt.refresh-token-expiration=604800000

# mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenducson2915@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# mongo db configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGO_DATABASE}

spring.jackson.time-zone=Asia/Ho_Chi_Minh
